name: karma_side_bar_flutter
version: 0.0.1
publish_to: none
author: No email noemail@noemail.com
description: This widget is designed for seamless navigation between different pages of the app.
homepage: https://github.com/yourusername/karma_side_bar
repository: https://github.com/yourusername/karma_side_bar

environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.6
  get: 4.6.6
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

